const theme = {
  primary: "var(--primary)",
  primaryDark: "var(--primaryDark)",
  primaryDarkest: "var(--primaryDarkest)",
  primaryLight: "var(--primaryLight)",
  primaryLightest: "var(--primaryLightest)",
  greyLightest: "var(--greyLightest)",
  greyLight: "var(--greyLight)",
  grey: "var(--grey)",
  greyDark: "var(--greyDark)",
  greyDarkest: "var(--greyDarkest)",
  textPrimary: "var(--textPrimary)",
  textSecondary: "var(--textSecondary)",
  textDisabled: "var(--textDisabled)",
  textSelectionBackground: "var(--textSelectionBackground)",
  textSelectionColor: "var(--textSelectionColor)",
  divider: "var(--divider)",
  greenText: "var(--greenText)",
  highlight: "var(--highlight)",
  interfaceColor: "var(--interfaceColor)",
  contentColor: "var(--contentColor)",
  board: "var(--board)",
  boardSearchbar: "var(--boardSearchbar)",
  boardPostShadow: "var(--boardPostShadow)",
  boardPostBackground: "var(--boardPostBackground)",
  primaryOverlay: "var(--primaryOverlay)",
  headerSearchbar: "var(--headerSearchbar)",
  headerShrunk: "var(--headerShrunk)",
  headerExpanded: "var(--headerExpanded)",
  threadPostBackground: "var(--threadPostBackground)",
  contentBorder: "var(--contentBorder)",
};

export default theme;
