---
language: node_js
node_js:
  - 6
# cache:
#   directories:
#   - node_modules
before_install:
  npm run uninstall && npm cache clean --force && npm install
install: true
branches:
  only:
  - master
  - develop
  - travis-ci
