sudo: required
dist: trusty

language: node_js

node_js:
  - 8

before_install:
  npm run uninstall && npm cache clean --force

install:
  npm install

branches:
  only:
    - master
    - develop
    - travis-ci
    - feature/ci-deployments

os:
  - linux
  - osx

script:
  - npm run publish:travis

addons:
  apt:
    packages:
    - build-essential
    - libxext-dev
    - libxtst-dev
    - libxkbfile-dev
