---
language: node_js
node_js:
  - 6
cache: false  # Enabling the cache seems to break travis.
  # directories:
  # - node_modules
  # - build/node_modules
install: true
branches:
  only:
  - master
  - develop
  - travis-ci
