---
language: node_js
node_js:
  - 6
  - 8
# cache:
#   directories:
#   - node_modules
#   - build/node_modules
before_install:
  npm run uninstall && npm cache clean --force && npm install
install:
  sudo npm install cross-env
  npm install
branches:
  only:
  - master
  - develop
  - travis-ci
