---
language: node_js
node_js:
  - 6
  - 8
cache:
  directories:
  - node_modules
  - build/node_modules
install:
  npm i cross-env
  npm install
branches:
  only:
  - master
  - develop
  - travis-ci
