export const APP_READY = "APP_READY"

export const TOGGLE_SETTINGS = "TOGGLE_SETTINGS"
export const TOGGLE_CONTENT_VIEW = "TOGGLE_CONTENT_VIEW"
export const OPEN_MEDIA_REEL = "OPEN_MEDIA_REEL"

export const THREAD_OPEN = "THREAD_OPEN"
export const THREAD_CLOSE = "THREAD_CLOSE"

export const SUB_HEADER_TOGGLE = "SUB_HEADER_TOGGLE"

export const RESET_BOARD = "RESET_BOARD"

export const OPEN_MODAL = "OPEN_MODAL"
export const CLOSE_MODAL = "CLOSE_MODAL"

export const SHRINK_HEADER = "SHRINK_HEADER"
export const EXPAND_HEADER = "EXPAND_HEADER"

export const OPEN_HEADER_PANEL = "OPEN_HEADER_PANEL"
export const CLOSE_HEADER_PANEL = "CLOSE_HEADER_PANEL"
