/* User settings */
// TODO: make user actions do stuff
export const USER_SAVED_POST = "USER_SAVED_POST"
export const USER_SAVED_MEDIA = "USER_SAVED_MEDIA"
export const USER_SAVED_BOARD = "USER_SAVED_BOARD"
export const USER_SAVED_THREAD = "USER_SAVED_THREAD"
export const USER_LOADED_ARCHIVE = "USER_LOADED_ARCHIVE"

/* Settings */
export const SETTINGS_LOADED = "SETTINGS_LOADED"
export const SETTINGS_SAVED = "SETTINGS_SAVED"

// TODO: make APP_INITIALISED work
export const APP_INITIALISED = "APP_INITIALISED"


/* Conetnt */
export const BOARD_CHANGED = "BOARD_CHANGED"
export const BOARD_REQUESTED = "BOARD_REQUESTED"
export const BOARD_LOADED = "BOARD_LOADED"
export const BOARD_DESTROYED = "BOARD_DESTROYED"
export const BOARD_LIST_LOADED = "BOARD_LIST_LOADED"
export const BOARD_LIST_REQUESTED = "BOARD_LIST_REQUESTED"
export const BOARD_SCROLLED_BOTTOM = "BOARD_SCROLLED_BOTTOM"

export const THREAD_REQUESTED = "THREAD_REQUESTED"
export const THREAD_LOADED = "THREAD_LOADED"
export const THREAD_DESTROYED = "THREAD_DESTROYED"
export const THREAD_SCROLLED_BOTTOM = "THREAD_SCROLLED_BOTTOM"


/* Header */
export const PROVIDER_CHANGED = "PROVIDER_CHANGED"
export const FILTER_BOARD = "FILTER_BOARD"
export const FILTER_THREAD = "FILTER_THREAD"
export const SEARCH_THREAD = "SEARCH_THREAD"
export const SERACH_BOARD = "SERACH_BOARD"
export const STATUS_MESSAGE_UPDATED = "STATUS_MESSAGE_UPDATED"


/* Animations */
export const LOGO_SPIN_STARTED = "LOGO_SPIN_STARTED"
export const LOGO_SPIN_ENDED = "LOGO_SPIN_ENDED"
export const PAGE_SCROLL_STARTED = "PAGE_SCROLL_STARTED"
export const PAGE_SCROLL_ENDED = "PAGE_SCROLL_ENDED"
