export const APP_READY = "APP_READY"

export const TOGGLE_SETTINGS = "TOGGLE_SETTINGS"
export const TOGGLE_CONTENT_VIEW = "TOGGLE_CONTENT_VIEW"
export const OPEN_MEDIA_REEL = "OPEN_MEDIA_REEL"

export const THREAD_OPEN = "THREAD_OPEN"
export const THREAD_CLOSE = "THREAD_CLOSE"
export const THREAD_MOVE = "THREAD_MOVE"

export const SUB_HEADER_TOGGLE = "SUB_HEADER_TOGGLE"

export const RESET_BOARD = "RESET_BOARD"

export const MODAL_OPEN = "MODAL_OPEN"
export const MODAL_CLOSE = "MODAL_CLOSE"

export const SHRINK_HEADER = "SHRINK_HEADER"
export const EXPAND_HEADER = "EXPAND_HEADER"
export const HEADER_TOGGLED = "HEADER_TOGGLED"

export const OPEN_HEADER_PANEL = "OPEN_HEADER_PANEL"
export const CLOSE_HEADER_PANEL = "CLOSE_HEADER_PANEL"
export const HEADER_PANEL_OPENED = "HEADER_PANEL_OPENED"
export const HEADER_PANEL_CLOSED = "HEADER_PANEL_CLOSED"

export const UPDATE_WATCH_ENTITY = "UPDATE_WATCH_ENTITY"

export const POST_TOGGLE = "POST_TOGGLE"

export const THEME_CHANGE = "THEME_CHANGE"

export const OPEN_CONTEXT_MENU = "OPEN_CONTEXT_MENU"
export const CLOSE_CONTEXT_MENU = "CLOSE_CONTEXT_MENU"
