export const APP_READY = "APP_READY"

export const TOGGLE_DRAWER = "TOGGLE_DRAWER"
export const TOGGLE_CONTENT_VIEW = "TOGGLE_CONTENT_VIEW"
export const OPEN_MEDIA_REEL = "OPEN_MEDIA_REEL"
export const THREAD_OPEN = "THREAD_OPEN"
export const THREAD_CLOSE = "THREAD_CLOSE"
